echo downloading driver...
wget -O led_driver.ko http://mikro-oving-3.googlecode.com/svn/trunk/driver/led_driver.ko 
echo removing old driver...
rmmod led_driver.ko
echo initializing driver...
insmod led_driver.ko
echo listing driver...
lsmod