echo Uninitializing old drivers...
rmmod ./stk1000_driver.ko

echo Downloading resources...
wget -O ./stk1000_driver.ko http://folk.ntnu.no/andereie/mikro/mikro-oving-3-read-only/driver/stk1000_driver.ko 

echo Initializing custom STK1000 driver...
insmod ./stk1000_driver.ko

echo Listing loaded drivers...
lsmod

echo Removing previous device...
rm -f /dev/stk1000_driver

echo Making node...
mknod /dev/stk1000_driver c 254 0

echo Changing permissions...
chmod a+rwx /dev/stk1000_driver