echo Uninitializing old drivers...
rmmod pong/led_driver.ko

echo Downloading resources...
wget -O pong/led_driver.ko http://mikro-oving-3.googlecode.com/svn/trunk/driver/led_driver.ko 
wget -O pong/pong.elf http://mikro-oving-3.googlecode.com/svn/trunk/src/pong.elf

echo Initializing custom STK1000 driver...
insmod pong/led_driver.ko

echo Listing loaded drivers...
lsmod

echo Removing previous device...
rm -f /dev/led_driver

echo Making node...
mknod /dev/led_driver c 254 0

echo Changing permissions...
chmod a+rwx /dev/led_driver
